<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20000303 Stylable//EN"
	"http://www.w3.org/TR/2000/03/WD-SVG-20000303/DTD/svg-20000303-stylable.dtd">
<svg width="50pt" height="50pt" viewBox="0 0 50 50" xml:space="preserve">
<g transform="scale(0.5)">
	<g id="M" style="fill-rule:none;clip-rule:nonzero;fill:none;stroke:#000000;stroke-miterlimit:4;fill-opacity:100%;">
		<path d="M49.00 58L49.00 31L58.00 45L67.00 23L67.00 50"/>
	</g>
	<g id="M Thicker Lines" style="fill-rule:none;clip-rule:nonzero;fill:none;stroke:#000000;stroke-miterlimit:4;fill-opacity:100%;">
		<path d="M47.00 59L47.00 32"/>
	</g>
	<g id="Path_2" style="fill-rule:none;clip-rule:nonzero;fill:none;stroke:#000000;stroke-miterlimit:4;fill-opacity:100%;">
		<path d="M49.00 33L58.00 47L67.00 25"/>
	</g>
	<g id="Path_3" style="fill-rule:none;clip-rule:nonzero;fill:none;stroke:#000000;stroke-miterlimit:4;fill-opacity:100%;">
		<path d="M69.00 22L69.00 49"/>
	</g>
</g>
</svg>